"""
Title generation via Ollama.

Uses Ollama JSON schema format for constrained structured output.
Caption is the primary input; a short transcript excerpt adds context
for thin-caption items. OCR is not used for title generation.

externals and summary are generated by the Claude pass (scripts/summarize.py).

Exposes:
  validate_title_config  — check Ollama is reachable
  generate_title         — returns {"title": str}
"""

import json
import logging

import ollama

from pipeline.config import Config

log = logging.getLogger(__name__)

# Single-field schema — constrained decoding, near-zero compliance failures.
_OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
    },
    "required": ["title"],
}

_SYSTEM_PROMPT = (
    "You are a content titling tool. "
    "Output only valid JSON matching the requested schema. "
    "Never add explanatory text or any content outside the JSON object."
)

_PROMPT_TEMPLATE = """Generate a concise, specific title for this saved Instagram post.

Author: {author} | Type: {type} | Collections: {collections}

Caption: {caption}

{transcript_line}

Title requirements:
- Max 80 characters
- Specific and descriptive — what the post actually covers
- Not the caption — extract the topic, not the words
- No filler framing ("how to", "tips for") unless it genuinely fits the content
"""


def validate_title_config(config: Config) -> None:
    """Raise RuntimeError if Ollama is not reachable."""
    try:
        client = ollama.Client(host=config.ollama_base_url)
        client.list()
    except Exception as exc:
        raise RuntimeError(
            f"Ollama not reachable at {config.ollama_base_url}. "
            f"Start with: ollama serve\nError: {exc}"
        ) from exc


def generate_title(config: Config, item: dict) -> dict:
    """
    Call Ollama to generate a title for one item.

    Caption is the primary input. A short transcript excerpt (first 300 chars)
    adds context for thin-caption Reels. OCR is not used.

    Returns {"title": str}.
    Raises RuntimeError on JSON parse failure (should not occur with constrained decoding).
    """
    transcript = (item.get("transcript") or "")[:300]
    transcript_line = f"Transcript (excerpt): {transcript}" if transcript else ""

    prompt = _PROMPT_TEMPLATE.format(
        author=item.get("author") or "[unknown]",
        type=item.get("type") or "[unknown]",
        collections=", ".join(item.get("collection") or []) or "[unclassified]",
        caption=item.get("caption") or "[none]",
        transcript_line=transcript_line,
    )

    client = ollama.Client(host=config.ollama_base_url)
    response = client.chat(
        model=config.ollama_model,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        format=_OUTPUT_SCHEMA,
    )

    try:
        result = json.loads(response.message.content)
    except (json.JSONDecodeError, TypeError) as exc:
        raise RuntimeError(
            f"titler: JSON parse failed for source_id={item.get('source_id')!r}. "
            f"Response: {response.message.content!r}"
        ) from exc

    log.debug("titler: ok for %s", item.get("source_id"))
    return {"title": str(result.get("title") or "").strip()}
