"""
Title generation CLI — Ollama local pass.

Per-item processing: Notion READ → Ollama → Notion WRITE (title field only).
Interrupt-safe: re-run skips items whose title is no longer a placeholder.

A placeholder title matches: "{author} — {shortcode}" (set at ingest).
externals and summary are generated by the Claude pass (scripts/summarize.py).

Runs on Queued AND Extracted items — title is decoupled from the status machine.
Does NOT change pipeline status.

Clean terminal = live progress bar; full detail → logs/title_<ts>.log.

Usage:
    python scripts/title.py              # all Queued + Extracted without real title
    python scripts/title.py --limit 5
    python scripts/title.py --source_id DYet7HfCwpj
    python scripts/title.py --dry-run
    python scripts/title.py --force      # overwrite existing title
"""

import logging
import re

from pipeline.config import load_config
from pipeline.notion import get_page_content, write_title
from pipeline.observability import StageProgress, setup_logging
from pipeline.runner import run_priority_stage
from pipeline.titler import generate_title, validate_title_config

log = logging.getLogger(__name__)

# Phase 1 placeholder format: "{author} — {shortcode}"
_PLACEHOLDER_RE = re.compile(r"^.+ — [A-Za-z0-9_-]+$")


def _is_placeholder(title: str | None) -> bool:
    if not title:
        return True
    return bool(_PLACEHOLDER_RE.match(title))


def _title_one(config, stub, dry_run, force, progress) -> str:
    """Process one item. Returns a counter name for the summary."""
    page_id = stub["page_id"]
    sid = stub.get("source_id", page_id)

    try:
        content = get_page_content(config, page_id)
    except Exception as exc:
        log.error("fetch failed for %s — %s", sid, exc)
        return "failed"

    if not force and not _is_placeholder(content.get("title")):
        log.info("%s already has real title — skipping", sid)
        return "skipped"

    if not content.get("caption") and not content.get("transcript"):
        log.info("%s has no caption or transcript — skipping", sid)
        return "skipped"

    try:
        result = generate_title(config, content)
    except Exception as exc:
        log.error("Ollama failed for %s — %s", sid, exc)
        return "failed"

    if dry_run:
        log.info("dry-run %s: title=%r", sid, result.get("title"))
        progress.log_line(f"[{sid}] {result.get('title')!r}")
        return "would_title"

    try:
        write_title(config, page_id, title=result["title"])
        log.info("titled %s", sid)
        return "titled"
    except Exception as exc:
        log.error("write failed for %s — %s", sid, exc)
        return "failed"


def run(limit=None, source_id=None, dry_run=False, force=False) -> None:
    config = load_config()
    validate_title_config(config)

    label = "Title (dry-run)" if dry_run else "Title"
    with StageProgress(label) as progress:
        def _process(config, item, ctx):
            return _title_one(config, item, dry_run, force, progress)

        # TODO(temp): expand to ("Extracted", "Imported") once set-2 extraction completes.
        for read_status in ("Extracted",):
            run_priority_stage(
                config,
                read_status,
                _process,
                progress,
                limit=limit,
                source_id=source_id,
                stage_key=f"title_{read_status.lower()}",
                bar_label=f"{read_status} items",
            )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Title generation: Ollama-based title for Queued and Extracted items."
    )
    parser.add_argument("--limit", type=int, metavar="N")
    parser.add_argument("--source_id", metavar="SHORTCODE")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true", help="Overwrite existing title.")
    args = parser.parse_args()

    log_path = setup_logging("title")
    run(limit=args.limit, source_id=args.source_id, dry_run=args.dry_run, force=args.force)
    print(f"\nlog: {log_path}")
